### ISSUE TITLE
Segmentation violation on startup

### ISSUE THREAD

**Issue by sharp004** [martabal/qbittorrent-exporter#37]
Hello Martin.

I'm very interested in your exporter because it allows me to obtain information by torrent file.
I'm using docker on a Nas Synology.

However, I have the following error on startup:

```
2024/03/24 22:22:58	stderr	goroutine 1 [running]:
2024/03/24 22:22:58	stderr	
2024/03/24 22:22:58	stderr	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x513bf8]
2024/03/24 22:22:58	stderr	panic: runtime error: invalid memory address or nil pointer dereference
2024/03/24 22:21:58	stderr	/app/src/init.go:30 +0x1f
2024/03/24 22:21:58	stderr	main.main()
2024/03/24 22:21:58	stderr	/app/src/init.go:74 +0x15d
2024/03/24 22:21:58	stderr	main.loadenv()
2024/03/24 22:21:58	stderr	/app/src/init.go:116 +0x8c
2024/03/24 22:21:58	stderr	main.getEnv({0x85859f?, 0xc0000780c0?}, {0x85238d, 0x5}, 0x1, {0x869930, 0x37})
2024/03/24 22:21:58	stderr	/usr/local/go/src/log/slog/logger.go:220
2024/03/24 22:21:58	stderr	log/slog.(*Logger).Warn(...)
2024/03/24 22:21:58	stderr	/usr/local/go/src/log/slog/logger.go:242 +0x6a
2024/03/24 22:21:58	stderr	log/slog.(*Logger).log(0x0, {0x8ffe58, 0xbfbb40}, 0x4, {0x869930, 0x37}, {0x0, 0x0, 0x0})
2024/03/24 22:21:58	stderr	/usr/local/go/src/log/slog/logger.go:169 +0x18
2024/03/24 22:21:58	stderr	log/slog.(*Logger).Enabled(0xc000004fb0?, {0x8ffe58?, 0xbfbb40?}, 0x7f63bcf59908?)
2024/03/24 22:21:58	stderr	/usr/local/go/src/log/slog/logger.go:122
2024/03/24 22:21:58	stderr	log/slog.(*Logger).Handler(...)
```

Do you have an idea of what could be the problem ?

**Comment by sharp004** [comment]
Ok I found the solution. The environment variable for the qbt user and password must be set, even if the default values are correct.
Working great thank you !

**Comment by martabal** [comment]
hello, even if it is not set, it should not have crashed, I opened a PR to fix that issue
